[package]
name = "wasm_rocket_game"
version = "0.1.0"
edition = "2025"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"
rand = "0.8.5"
pcg_rand = "0.13.0"
itertools-num = "0.1.3"
lazy_static ="1.5.0"
getrandom = { version = "0.2", features = ["js"] }